run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive
    - errorlint
  disable-all: true

linters-settings:
  gofmt:
    simplify: true
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: package-comments
      - name: blank-imports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0